name: overclock_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.5
  carousel_slider: ^4.2.1
  firebase_auth: ^4.2.9
  firebase_core: ^2.5.0
  cloud_firestore: ^4.4.2
  async: ^2.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  expandable: ^5.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/