// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXKy_E-HEeWWLYxzNNlqe4WhDD_HL_tqo',
    appId: '1:351051379750:web:728feb1dd7ee7f7c77e2e7',
    messagingSenderId: '351051379750',
    projectId: 'overclock-app',
    authDomain: 'overclock-app.firebaseapp.com',
    storageBucket: 'overclock-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUnlxNTBQzxY_t7nlF8_dBOz1ZHaJc3Ak',
    appId: '1:351051379750:android:0168e3c494c3004f77e2e7',
    messagingSenderId: '351051379750',
    projectId: 'overclock-app',
    storageBucket: 'overclock-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ2vfowfcuYw6G1hetGlBCf3AYboq30_A',
    appId: '1:351051379750:ios:d9ea840f4b18c49e77e2e7',
    messagingSenderId: '351051379750',
    projectId: 'overclock-app',
    storageBucket: 'overclock-app.appspot.com',
    iosClientId: '351051379750-4e92m2a574i4ktsfgfl2i7ve3g6nn2gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.overclockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ2vfowfcuYw6G1hetGlBCf3AYboq30_A',
    appId: '1:351051379750:ios:d9ea840f4b18c49e77e2e7',
    messagingSenderId: '351051379750',
    projectId: 'overclock-app',
    storageBucket: 'overclock-app.appspot.com',
    iosClientId: '351051379750-4e92m2a574i4ktsfgfl2i7ve3g6nn2gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.overclockApp',
  );
}
